Add schedules to modbus-quick-start.md
osisoft/Edge-Data-Store-Docs pull request #217
Opened 2022-03-25 17:01 UTC by bbilbrey-aveva

2022-03-28 12:56 UTC, bballentine123 requested changes

2022-03-28 12:56 UTC, bballentine123 commented on content/overview/modbus-quick-start.md
> +1.  Using a text editor, copy the example below to create a file in JSON format to describe the location of the Modbus TCP data source.
This line should be updated to talk about the schedules

2022-03-28 12:56 UTC, bballentine123 commented on content/overview/modbus-quick-start.md
> +   curl -d "@Modbus1Schedules.json.json" -H "Content-Type: application/json" -X PUT http://localhost:5590/api/v1/configuration/Modbus1/Schedules
There's a double '.json' in the file name here

2022-03-31 23:49 UTC, osisoft-mbishop approved these changes

2022-03-31 23:50 UTC, merged